# model_name_or_path:  '../result/CoT-LMF' # 预训练模型路径
# tokenizer_name: ''  # 若需覆盖默认分词器则指定名称
# pooler: 'cls'  # options: cls, cls_before_pooler, avg, avg_first_last
# mask_num: 2  # 掩码标记数量
# mask_embedding_sentence: false  # 是否启用句子级掩码嵌入
# mask_embedding_sentence_template: '*cls*_The_sentence_of_"*sent_0*"_means_*mask*_,_so_it_can_be_summarized_as_*mask*_._*sep+*'  # 自定义模板字符串（若需启用则替换）
# mask_embedding_sentence_use_org_pooler: false  # 使用原始池化层
# mask_embedding_sentence_delta: false  # 是否应用差值计算
# mask_embedding_sentence_autoprompt: false  # 自动提示模板生成
# mask_embedding_sentence_use_pooler: false  # 使用独立池化层
# embedding_only: false  # 仅提取嵌入不微调
# mlm_head_predict: false  # 启用MLM头部预测
# remove_continue_word: false  # 移除连续重复词
# mask_embedding_sentence_org_mlp: false  # 使用原始MLP结构
# calc_anisotropy: false  # 计算嵌入各向异性
# mode: 'test'  # options: dev, test, fasttest
# task_set: 'sts'  # options: sts, transfer, full, na

model_name_or_path: '../result/CoT-LMF'
tokenizer_name: ''
pooler: 'cls'
mask_num: 2
mask_embedding_sentence_num_masks: 2
mask_embedding_sentence_template: '*cls*_The_sentence_of_"*sent_0*"_means_*mask*_,_so_it_can_be_summarized_as_*mask*_._*sep+*'
mode: 'test'
task_set: 'sts'
mask_embedding_sentence_org_mlp: false