mask_pool_type: "default" # sum, mean, max, default
model_name_or_path: "/workspace/pretrain_models/bert-base-uncased"
train_file: "../data/wiki1m_for_simcse.txt"
output_dir: "../result/CoT-LMF"
num_train_epochs: 1
per_device_train_batch_size: 128
gradient_accumulation_steps: 1
learning_rate: 1e-5
max_seq_length: 32
evaluation_strategy: steps
metric_for_best_model: stsb_spearman
load_best_model_at_end: true
eval_steps: 10
overwrite_output_dir: true
temp: 0.05
do_train: true
fp16: true
preprocessing_num_workers: 10
mlp_only_train: true
mask_embedding_sentence: true
mask_num: 3
mask_num_embedding_sentence_different_template: 3
mask_embedding_sentence_template: '*cls*_The_sentence_of_"*sent_0*"_means_*mask*_and_*mask*,_so_it_can_be_summarized_as_*mask*_._*sep+*'
mask_embedding_sentence_different_template: '*cls*_The_sentence_of_"*sent_0*"_means_*mask*_,_does_not_mean_*mask*_,_so_it_can_be_summarized_as_*mask*_._*sep+*'
# mask_embedding_sentence_different_template: '*cls*_The_sentence_:_"*sent_0*"_means_*mask*_,_so_it_can_be_summarized_as_*mask*_._*sep+*'
mask_embedding_sentence_negative_template: '*cls*_The_sentence_:_"*sent_0*"_does_not_mean_*mask*_and_*mask*_,_so_it_cannot_be_summarized_as_*mask*_._*sep+*'
mask_embedding_sentence_different_negative_template: ''
mask_embedding_sentence_delta_no_delta_eval: true
mask_embedding_sentence_delta: true
dataloader_drop_last: true
seed: 0
