model_name_or_path: "/data/output/workspace_gpu4/pretrain_models/bert-base-uncased"
per_device_train_batch_size: 64
gradient_accumulation_steps: 2
mask_pool_type: "default" # sum, mean, max, default
mask_num: 3
mask_num_embedding_sentence_different_template: 3
mask_embedding_sentence_template: '*cls*_The_sentence_of_"*sent_0*"_means_*mask*_and_*mask*,_so_it_can_be_summarized_as_*mask*_._*sep+*'
mask_embedding_sentence_different_template: '*cls*_The_sentence_of_"*sent_0*"_means_*mask*_,_does_not_mean_*mask*_,_so_it_can_be_summarized_as_*mask*_._*sep+*'
# mask_embedding_sentence_different_template: '*cls*_The_sentence_:_"*sent_0*"_means_*mask*_,_so_it_can_be_summarized_as_*mask*_._*sep+*'
mask_embedding_sentence_negative_template: '*cls*_The_sentence_:_"*sent_0*"_does_not_mean_*mask*_and_*mask*_,_so_it_cannot_be_summarized_as_*mask*_._*sep+*'

