model_name_or_path: "../result/CoT-Bert"
mode: test
mask_embedding_sentence: true
mask_num: 2
mask_embedding_sentence_template: 'The_sentence_of_*cls*_"*sent_0*"_*sep+*_means_*mask*_,_so_it_can_be_summarized_as_*mask*_.'
mask_embedding_sentence_delta: false
task_set: sts

