model_name_or_path: "bert-base-uncased"
train_file: "../data/hard_negatives_masked.tsv"
output_dir: "../result/CoT-Bert"
num_train_epochs: 1
per_device_train_batch_size: 64
gradient_accumulation_steps: 1
learning_rate: 1e-5
max_seq_length: 32
evaluation_strategy: steps
metric_for_best_model: stsb_spearman
load_best_model_at_end: true
eval_steps: 125

save_strategy: steps
save_steps: 125
save_total_limit: 1

logging_steps: 10

overwrite_output_dir: true
do_train: true
fp16: false
preprocessing_num_workers: 8
use_mps_device: false
dataloader_drop_last: true
seed: 0
overwrite_cache: false

# CoT-BERT specific arguments
temp: 0.05
scd_temp: 0.05
mlp_only_train: true

# SAN-style custom dropout for last column (BertEmbeddings)
enable_custom_dropout_for_last_column: false
hidden_dropout_prob_for_last_column: 0.1
num_columns: 2
dropout_different_prob: 0.1
dropout_negative_prob: 0.1

mask_embedding_sentence: true
mask_num: 2
mask_embedding_sentence_template: 'The_sentence_of_*cls*_"*sent_0*"_*sep+*_means_*mask*_,_so_it_can_be_summarized_as_*mask*_.'
mask_embedding_sentence_different_template: 'Regarding_the_sentence_of_*cls*_"*sent_0*"_*sep+*,_its_core_idea_is_*mask*_,_which_sums_up_as_*mask*_.'
mask_embedding_sentence_negative_template: 'The_sentence_of_*cls*_"*sent_0*"_*sep+*_does_not_mean_*mask*_,_so_it_can_not_be_summarized_as_*mask*_.'
mask_embedding_sentence_different_negative_template: ''
mask_embedding_sentence_delta_no_delta_eval: true
mask_embedding_sentence_delta: true

