model_name_or_path: "/data/output/workspace_gpu2/pretrain_models/bert-base-uncased"
train_file: "../data/hard_negatives_masked.tsv"
output_dir: "../result/CoT-Bert"
num_train_epochs: 1
per_device_train_batch_size: 16
gradient_accumulation_steps: 4
learning_rate: 1e-5
max_seq_length: 32
evaluation_strategy: steps
metric_for_best_model: stsb_spearman
load_best_model_at_end: true
eval_steps: 10

save_strategy: steps
save_steps: 10
save_total_limit: 1

logging_steps: 10

overwrite_output_dir: true
do_train: true
fp16: false
preprocessing_num_workers: 10
use_mps_device: false
dataloader_drop_last: true
seed: 0
overwrite_cache: false

# CoT-BERT specific arguments
temp: 0.05
scd_temp: 0.1
mlp_only_train: true

# SAN-style custom dropout for last column (BertEmbeddings)
enable_custom_dropout_for_last_column: true
hidden_dropout_prob_for_last_column: 0.2
num_columns: 3
dropout_different_prob: 0.1
dropout_negative_prob: 0.1

mask_embedding_sentence: true
mask_num: 2
mask_embedding_sentence_template: '*cls*_The_sentence_of_"*sent_0*"_means_*mask*_,_so_it_can_be_summarized_as_*mask*_._*sep+*'
mask_embedding_sentence_different_template: '*cls*_The_sentence_:_"*sent_0*"_means_*mask*_,_so_it_can_be_summarized_as_*mask*_._*sep+*'
mask_embedding_sentence_negative_template: '*cls*_The_sentence_:_"*sent_0*"_does_not_mean_*mask*_,_so_it_cannot_be_summarized_as_*mask*_._*sep+*'
mask_embedding_sentence_different_negative_template: ''
mask_embedding_sentence_delta_no_delta_eval: true
mask_embedding_sentence_delta: true

