model_name_or_path: "/Users/lmf/Documents/local/code/pretrain_models/bert-base-uncased"
train_file: "../data/wiki1m_for_simcse.txt"
output_dir: "../result/ProcessSupervisionCoT-BERT-mac_m4"

num_train_epochs: 1
per_device_train_batch_size: 16
gradient_accumulation_steps: 4
learning_rate: 1e-5
max_seq_length: 32
evaluation_strategy: steps
metric_for_best_model: eval_stsb_spearman
load_best_model_at_end: true
eval_steps: 125

save_strategy: steps
save_steps: 125
save_total_limit: 1

overwrite_output_dir: true
do_train: true
fp16: false
preprocessing_num_workers: 4
use_mps_device: false
dataloader_drop_last: true
seed: 0

temperature: 0.05
temp: 0.05

mask_embedding_sentence: true
mask_num: 2
mask_embedding_sentence_template: '*cls*_The_sentence_:_"*sent_0*"_means_*mask*_,_so_it_can_be_summarized_as_*mask*_._*sep+*'
mask_embedding_sentence_different_template: '*cls*_The_sentence_:_"*sent_0*"_means_*mask*_,_so_it_can_be_summarized_as_*mask*_._*sep+*'
mask_embedding_sentence_negative_template: '*cls*_The_sentence_:_"*sent_0*"_does_not_mean_*mask*_,_so_it_cannot_be_summarized_as_*mask*_._*sep+*'

cross_template_weight: 0.5
process_supervision_weight: 0.1
enable_process_supervision: false


