# Linux NVIDIA CUDA 训练配置
model_name_or_path: "/path/to/pretrain_models/bert-base-uncased"
train_file: "../data/wiki1m_for_simcse.txt"
output_dir: "../result/SPR-BERT"
num_train_epochs: 1
per_device_train_batch_size: 64
gradient_accumulation_steps: 2
learning_rate: 1e-5
max_seq_length: 32
evaluation_strategy: no
save_steps: 125
overwrite_output_dir: true
do_train: true
fp16: true  # 启用混合精度训练
preprocessing_num_workers: 16  # 更多工作进程
use_mps_device: false
dataloader_drop_last: true
seed: 0

# SPR specific arguments
prompt_template: 'The sentence of "[X]" means [MASK], and also means [MASK].'
mask_num: 2
spr_denoising: true

# CUDA 特定设置
# device, no_cuda, use_cpu 参数由平台工具自动处理
dataloader_num_workers: 8
